version: "3.8"

services:
  frontend:
    build: my-react-app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: backend
    ports:
      - "5000:5000"
  #   depends_on:
  #     - database

  # database:
  #   image: mysql:5.7
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: users
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - dbdata:/var/lib/mysql

volumes:
  dbdata:
