# Use official Python image as base image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install pkg-config
# Install pkg-config and other necessary build tools
RUN apt-get update && apt-get install -y build-essential pkg-config


# Set working directory
WORKDIR /app

# Copy and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY . .

# Expose port 5000 for Flask app and 3306 for MySQL
EXPOSE 5000
EXPOSE 3306

# Command to start MySQL server and Flask application
# Command to start the Flask application
CMD ["python", "app.py"]